import Header from '@/components/header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sistema Listado de Repuestos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/yeti/bootstrap.min.css" />
      </head>
      <body className={inter.className}>
        <Header/>
        <div className="container p-4">
        {children}
        </div>
      </body>
    </html>
  )
}
